In [1]:
import numpy as np

In [31]:
m = np.array([0.506, 0.503, 0.500, 0.513])
x = np.array([13, 13, 13, 13])
m_err = 0.001
M = 2900
M_err = 5
x_err = 0.25 
L = 2.215
L_err = 0.005
g =9.8155
g_err = 0.0005

In [32]:
u = M/m * np.sqrt(g/L) * x * 1e-3
np.mean(u)

157.0105580730137

In [34]:
np.mean(u)

157.0105580730137

In [5]:
eps_M = M_err / M
eps_m = m_err / m
eps_g = g_err / g
eps_L = L_err / L
eps_x = x_err / x
u_err = u * np.sqrt(eps_M**2 + eps_m ** 2 + 0.25*eps_g**2 + 0.25*eps_L**2 + eps_x**2)
u_err

array([3.04924231, 3.06761825, 3.08752496, 3.0072135 ])

In [48]:
# new block

T1 = np.array([36.69, 36.77, 36.03])/2
T2 = np.array([41.75, 42.01, 41.89])/3

T1_m = np.mean(T1)
T2_m = np.mean(T2)
T1_err = np.std(T1)
T2_err = np.std(T2)

M = (714.2 + 713.9)/2

R = 34
r = 23.1
d = 43

R_err = 0.2
r_err = 0.2
d_err = 0.5

m = np.array([0.510, 0.504, 0.501, 0.515])
# x = np.array([11.0, 12.5, 11.5, 11.3])
x = np.array([11.2, 11.5, 11.5, 11.3])

x_err = 0.2

phi = x / (d*2)
phi_err = phi * np.sqrt((x_err/x)**2 + (d_err/d)**2)

kI = 4*np.pi*M*R**2*T1_m/(T1_m**2-T2_m**2)
kI_err = kI*np.sqrt((2*R_err/R)**2 + (2*T2_m*T2_err/(T1_m**2 - T2_m**2))**2 + ((T1_m**2 + T2_m**2)*T1_err/(T1_m**2 - T2_m**2)/T1_m)**2**2)

u = phi*kI/(m*r)
u_err = u * np.sqrt((kI_err/kI)**2 + (r_err/r)**2 + (phi_err/phi)**2)
print(f"{kI} +- {kI_err}, g*cm^2/s\n")
print(u * 0.01)
print(u_err * 0.01)

1370756.4489079304 +- 18951.61247501155, g*cm^2/s

[151.52968248 157.44075746 158.38351649 151.39832873]
[4.06652075 4.17670975 4.20171999 4.04711515]


In [40]:
np.mean(u) * 0.01

154.6880712911908