In [9]:
import numpy as np
import pandas as pd
from array import array

In [20]:
# Load data
filename = "calib.csv"
data = pd.read_csv(filename, engine='python', sep = ';', header=None)

In [22]:
y = np.array(data[1])
t = np.array(data[0])
d = np.array(data[2])

In [25]:
d

array([5400, 5828, 5885, 5944, 5975, 6030, 6074, 6096, 6143, 6163, 6217,
       6266, 6304, 6334, 6382, 6402, 6506, 6532, 6598, 6678, 6717, 6929,
       7032])

In [39]:
x = array('d')
x.fromlist(list(y))

In [40]:
x

array('d', [1872.0, 2130.0, 2146.0, 2174.0, 2192.0, 2218.0, 2235.0, 2248.0, 2266.0, 2274.0, 2298.0, 2318.0, 2334.0, 2346.0, 2363.0, 2372.0, 2412.0, 2418.0, 2440.0, 2466.0, 2478.0, 2544.0, 2575.0])

In [41]:
type(x)

array.array

In [42]:
type(d)

numpy.ndarray

In [43]:
data

0     1     2
0   23  1872  5400
1   22  2130  5828
2   21  2146  5885
3   20  2174  5944
4   19  2192  5975
5   18  2218  6030
6   17  2235  6074
7   16  2248  6096
8   15  2266  6143
9   14  2274  6163
10  13  2298  6217
11  12  2318  6266
12  11  2334  6304
13  10  2346  6334
14   9  2363  6382
15   8  2372  6402
16   7  2412  6506
17   6  2418  6532
18   5  2440  6598
19   4  2466  6678
20   3  2478  6717
21   2  2544  6929
22   1  2575  7032

In [44]:
type(data)

pandas.core.frame.DataFrame

In [48]:
len(x)

23

In [55]:
filename = "calib.csv"
data = pd.read_csv(filename, engine='python', sep = ';', header=None)

x = array('d')
ex = array('d')
y = array('d')
ey = array('d')

x.fromlist(list(np.array(data[1])))
y.fromlist(list(np.array(data[2])))
ex.fromlist(list(np.array(data[3])))
ey.fromlist(list(np.zeros(len(y))))

SyntaxError: unexpected EOF while parsing (<ipython-input-55-d02324acd7b0>, line 12)

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
len(y)

23

In [54]:
list(np.zeros(len(y)))

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [93]:
import ROOT
from ROOT import gROOT

In [116]:
filename = "calib.csv"
data = pd.read_csv(filename, engine='python', sep = ';', header=None)

x = array('d')
ex = array('d')
y = array('d')
ey = array('d')

x.fromlist(list(np.array(data[1])))
y.fromlist(list(np.array(data[2])))
ex.fromlist(list(np.array(data[3])))
ey.fromlist(list(np.zeros(len(y))))

c1 = ROOT.TCanvas('c1', 'A Simple Graph with error bars', 200, 10, 700, 500)

c1.SetGrid()
c1.GetFrame().SetFillColor( 21 )
c1.GetFrame().SetBorderSize( 12 )

gr = ROOT.TGraphErrors( len(x), x, y, ex, ey )

Warning in <TCanvas::Constructor>: Deleting canvas with same name: c1


In [72]:
class myPol1:
    def __call__( self, t, par ):
        #y = a*x + b
        a = par[0] 
        b = par[1] 
        x = t[0]   
        return a * x + b

In [96]:
ff = ROOT.TF1('ff', 'pol2', 1700, 2800)
ff.SetParameters( 7.6e+02, -3.7, 1.e-03)

In [97]:
gr.Fit('ff', 'SRF')

 FCN=0.478037 FROM MIGRAD    STATUS=CONVERGED     205 CALLS         206 TOTAL
                     EDM=5.14216e-08    STRATEGY= 1      ERROR MATRIX ACCURATE 
  EXT PARAMETER                                   STEP         FIRST   
  NO.   NAME      VALUE            ERROR          SIZE      DERIVATIVE 
   1  p0           7.60904e+03   9.67807e+02   6.55664e-03  -2.09451e-05
   2  p1          -3.70535e+00   8.98735e-01   2.95664e-06  -4.71015e-02
   3  p2           1.34934e-03   2.07839e-04   1.31464e-09  -1.07620e+02


In [105]:
fited = gr.Fit('ff', 'SRF')

 FCN=0.478037 FROM MIGRAD    STATUS=CONVERGED      41 CALLS          42 TOTAL
                     EDM=1.6168e-08    STRATEGY= 1      ERROR MATRIX ACCURATE 
  EXT PARAMETER                                   STEP         FIRST   
  NO.   NAME      VALUE            ERROR          SIZE      DERIVATIVE 
   1  p0           7.60904e+03   7.94680e+02   8.09124e-03   7.64618e-07
   2  p1          -3.70535e+00   7.36747e-01   7.51069e-06   1.24923e-03
   3  p2           1.34934e-03   1.70465e-04   1.73939e-09   8.20986e-01


In [101]:
fited

In [104]:
fited.Ndf()

20

In [103]:
fited.Chi2()

0.4780365097559479

In [138]:
filename = "2318.csv"
data = pd.read_csv(filename, engine='python', sep = ';', header=None)

x = array('d')
ex = array('d')
y = array('d')
ey = array('d')

x.fromlist(list(np.array(data[1])))
y.fromlist(list(np.array(data[4])))
ex.fromlist(list(np.array(data[3])))
ex.fromlist(list(np.array(data[5])))

In [136]:
nx= np.array(data[1])

In [137]:
nx

array([ 0.77 ,  0.55 ,  0.358,  0.083, -0.022, -0.147, -0.45 ])

In [132]:
nx.dtype

dtype('O')

In [139]:
x

array('d', [0.77, 0.55, 0.358, 0.083, -0.022000000000000002, -0.147, -0.45])

In [140]:
y

array('d', [0.539, 0.48, 0.4, 0.27699999999999997, 0.228, 0.16399999999999998, 0.055])

In [141]:
ex

array('d', [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.04, 0.04, 0.039, 0.038, 0.037000000000000005, 0.037000000000000005, 0.036000000000000004])

In [142]:
ey

array('d')